[workspace]
authors = ["ILikeNickelback <christopher.larran@gmail.com>"]
channels = ["conda-forge"]
name = "OpenJTS"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
test = "pytest software/tests"

[dependencies]
python = "3.14.*"
numpy = ">=2.4.6,<3"
pytest = ">=9.0.3,<10"
pylint = ">=4.0.5,<5"
ruff = ">=0.15.17,<0.16"
loguru = ">=0.7.3,<0.8"
mcculw = ">=1.0.0,<2"
matplotlib = ">=3.11.0,<4"
pyserial = ">=3.5,<4"
