"""Base window abstraction for DearPyGui windows.

All application windows inherit from :class:`WindowBase`, which handles
identity (label, UUID, DPG tag) and geometry (position, size, visibility).
Subclasses build their UI in a ``_buildui`` method and call ``super().__init__``
to ensure consistent setup.
"""

import dearpygui.dearpygui as dpg


class WindowBase:
    """Base class for all DearPyGui windows in the application.

    Handles identity and geometry; subclasses build their UI in a ``_buildui``
    method and call ``super().__init__`` to ensure consistent setup.

    Attributes:
        label (str): Human-readable window title.
        pos (tuple[int, int]): Initial (x, y) screen position.
        win_width (int): Initial window width; -1 lets DPG size automatically.
        win_height (int): Initial window height; -1 lets DPG size automatically.
        visible (bool): Whether the window is shown on creation.
        UUID (str): Unique identifier, either provided or generated by DPG.
        winID (str): DPG item tag, formed as ``"<label>_<UUID>"``.
    """

    def __init__(
        self,
        label="Window",
        pos=(10, 10),
        win_width=-1,
        win_height=-1,
        uuid=None,
        visible=True,
    ):
        """Initialise window identity and geometry attributes.

        Args:
            label (str): Window title displayed in the DPG title bar.
            pos (tuple[int, int]): Initial (x, y) position on screen.
            win_width (int): Initial width in pixels; -1 for automatic sizing.
            win_height (int): Initial height in pixels; -1 for automatic sizing.
            uuid (str | None): Explicit UUID to assign; auto-generated if None.
            visible (bool): Whether the window starts visible.
        """
        self.label = label
        self.pos = pos
        self.win_width = win_width
        self.win_height = win_height
        self.visible = visible
        self.UUID = uuid or str(dpg.generate_uuid())
        self.winID = f"{label}_{self.UUID}"

    def close(self):
        """Delete the DPG window item if it still exists."""
        if dpg.does_item_exist(self.winID):
            dpg.delete_item(self.winID)
